-- Push tokens: one row per device token, linked to auth user
create table if not exists public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  push_token text not null unique,
  updated_at timestamptz default timezone('utc'::text, now()) not null
);

alter table public.user_push_tokens enable row level security;

drop policy if exists "Users manage own push tokens" on public.user_push_tokens;
create policy "Users manage own push tokens"
  on public.user_push_tokens
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Notifications table (skip if you already created it in the dashboard)
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  title text,
  message text,
  type text,
  related_id uuid,
  is_read boolean default false,
  created_at timestamptz default now()
);

alter table public.notifications enable row level security;

drop policy if exists "Users read own notifications" on public.notifications;
create policy "Users read own notifications"
  on public.notifications for select
  using (auth.uid() = user_id);

drop policy if exists "Users update own notifications" on public.notifications;
create policy "Users update own notifications"
  on public.notifications for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Reports + attachments (skip if already applied)
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id),
  species_id uuid references public.mangrove_species(id),
  image_url text,
  health_status text check (health_status in ('healthy', 'unhealthy')),
  latitude double precision,
  longitude double precision,
  location_text text,
  field_notes text,
  status text default 'pending'
    check (status in ('pending', 'under_review', 'resolved', 'rejected', 'recorded')),
  created_at timestamptz default now()
);

create table if not exists public.report_attachments (
  id uuid primary key default gen_random_uuid(),
  report_id uuid references public.reports(id) on delete cascade,
  image_url text,
  created_at timestamptz default now()
);

-- Notify all admins when a volunteer submits a report
create or replace function public.notify_admins_on_new_report()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_record record;
begin
  for admin_record in
    select id from public.users where role = 'admin'
  loop
    insert into public.notifications (user_id, title, message, type, related_id)
    values (
      admin_record.id,
      'New Report Submitted',
      'A volunteer has submitted a new mangrove health report for review.',
      'new_report',
      NEW.id
    );
  end loop;
  return NEW;
end;
$$;

drop trigger if exists on_report_created_notify_admins on public.reports;
create trigger on_report_created_notify_admins
  after insert on public.reports
  for each row execute function public.notify_admins_on_new_report();

-- Notify volunteer when admin changes report status
create or replace function public.notify_volunteer_on_report_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if TG_OP = 'UPDATE' and OLD.status is distinct from NEW.status then
    insert into public.notifications (user_id, title, message, type, related_id)
    values (
      NEW.user_id,
      case NEW.status
        when 'under_review' then 'Report Approved'
        when 'rejected' then 'Report Rejected'
        when 'resolved' then 'Report Resolved'
        else 'Report Update'
      end,
      case NEW.status
        when 'under_review' then 'Your mangrove report has been verified and is now active on the map.'
        when 'rejected' then 'Your report was reviewed and could not be approved.'
        when 'resolved' then 'Your submitted report has been marked as resolved.'
        else 'Your report status has been updated.'
      end,
      case NEW.status
        when 'under_review' then 'approved'
        when 'rejected' then 'rejected'
        when 'resolved' then 'resolved'
        else 'update'
      end,
      NEW.id
    );
  end if;
  return NEW;
end;
$$;

drop trigger if exists on_report_status_change_notify_volunteer on public.reports;
create trigger on_report_status_change_notify_volunteer
  after update of status on public.reports
  for each row execute function public.notify_volunteer_on_report_status_change();

-- Enable Realtime for in-app notification badges (optional but recommended)
alter publication supabase_realtime add table public.notifications;
